[package]
org = "tharmigan"
name = "llp_to_db_file_email"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "messaging"
version = "1.0.0"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "rabbitmq"
version = "3.3.0"
repository = "local"

[[dependency]]
org = "xlibb"
name = "pipeline"
version = "0.1.0"
repository = "local"
